server:
  port: 8083

spring:
  application:
    name: PAYMENT-SERVICE
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance: localhost
